FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat curl
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npx","serve@latest","out","-l","3000"]
