import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — LexyAlgo',
  description: 'LexyAlgo terms of service. Rules governing your use of our document preparation tools.',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
      <h1 className="font-[family-name:var(--font-space)] text-3xl sm:text-4xl font-bold text-slate-900">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: March 26, 2026</p>

      <div className="mt-10 prose prose-slate max-w-none prose-headings:font-[family-name:var(--font-space)] prose-headings:font-bold prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-4 prose-p:text-slate-600 prose-p:leading-relaxed prose-li:text-slate-600">

        <h2>1. What LexyAlgo Is (and Isn&rsquo;t)</h2>
        <p>
          LexyAlgo is a <strong>document preparation service</strong>. We provide software tools that help you create legal documents based on information you provide. We are <strong>not a law firm</strong>. No attorney-client relationship is created by using our services.
        </p>
        <p>
          Our tools do not constitute legal advice. We cannot tell you whether to file for divorce, how to divide your assets, or what custody arrangement to pursue. For guidance specific to your situation, consult a licensed attorney in your jurisdiction.
        </p>

        <h2>2. Acceptance of Terms</h2>
        <p>
          By accessing or using LexyAlgo (the &ldquo;Service&rdquo;), you agree to these Terms of Service. If you do not agree, do not use the Service. We may update these terms; continued use after changes constitutes acceptance.
        </p>

        <h2>3. Your Responsibilities</h2>
        <ul className="space-y-2">
          <li><strong>Accuracy:</strong> You are responsible for the accuracy of all information you enter. Our documents are generated based on your input — incorrect input produces incorrect documents.</li>
          <li><strong>Review:</strong> You should review all generated documents before filing them with any court. We recommend having a licensed attorney review documents before submission.</li>
          <li><strong>Compliance:</strong> You are responsible for ensuring that documents comply with your local court&rsquo;s specific requirements, which may change without notice.</li>
          <li><strong>Account security:</strong> You are responsible for maintaining the confidentiality of your account credentials.</li>
        </ul>

        <h2>4. No Guarantee of Court Acceptance</h2>
        <p>
          We generate documents based on publicly available court forms and general legal requirements. However, <strong>we cannot guarantee that any court will accept, approve, or sign any document</strong> generated by our service. Courts have discretion, local rules vary, and individual judges may have specific requirements.
        </p>

        <h2>5. Payments and Refunds</h2>
        <p>
          Certain services require payment (e.g., QDRO generation at $100 per order). Prices are listed on the applicable product page. All payments are processed through third-party payment providers.
        </p>
        <p>
          If a generated document contains an error caused by our system (not by incorrect user input), we will regenerate the document at no charge. We do not offer refunds for documents that are rejected by a court due to user error, local rule changes, or judicial discretion.
        </p>

        <h2>6. Intellectual Property</h2>
        <p>
          Documents generated by the Service are yours. You own the content you create. The LexyAlgo platform, software, design, and branding remain our intellectual property. You may not copy, modify, or redistribute our software or interface.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, LexyAlgo&rsquo;s total liability for any claim arising from use of the Service is limited to the amount you paid for the specific service giving rise to the claim, or $100, whichever is greater.
        </p>
        <p>
          We are not liable for indirect, incidental, consequential, or punitive damages, including but not limited to: court rejection of documents, delays in legal proceedings, loss of rights due to missed deadlines, or emotional distress.
        </p>

        <h2>8. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available.&rdquo; We make no warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that documents will meet your specific legal needs.
        </p>

        <h2>9. Privacy</h2>
        <p>
          Your use of the Service is governed by our <Link href="/privacy" className="text-teal hover:underline">Privacy Policy</Link>, which describes how we collect, use, and protect your information.
        </p>

        <h2>10. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time for violation of these terms or for any other reason. You may stop using the Service at any time. Upon termination, your right to use the Service ceases, but provisions that by their nature should survive (limitation of liability, disclaimers, etc.) will survive.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These terms are governed by the laws of the State of Connecticut, without regard to conflict of law provisions. Any disputes arising from these terms or the Service shall be resolved in the courts of New Haven County, Connecticut.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these terms? Contact us at{' '}
          <a href="mailto:legal@lexyalgo.com" className="text-teal hover:underline">legal@lexyalgo.com</a>{' '}
          or visit our <Link href="/contact" className="text-teal hover:underline">contact page</Link>.
        </p>
      </div>
    </div>
  )
}
